services:
  - type: web
    name: hr-compliance-app
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///./hr_compliance.db
    disk:
      name: hr-app-disk
      mountPath: /opt/render/project/src/backend
      sizeGB: 10